### ISSUE TITLE
Crash when scanning balance on startup

### ISSUE THREAD

**Issue by infernix** [Samourai-Wallet/samourai-wallet-android#131]
Newly created empty wallet with passphrase:

```
03-02 17:15:55.844 32364 32364 E AndroidRuntime: FATAL EXCEPTION: main
03-02 17:15:55.844 32364 32364 E AndroidRuntime: Process: com.samourai.wallet, PID: 32364
03-02 17:15:55.844 32364 32364 E AndroidRuntime: java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.view.InputChannel.nativeReadFromParcel(Native Method)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.view.InputChannel$1.createFromParcel(InputChannel.java:37)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:68)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:112)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:110)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at com.android.internal.view.IInputMethodManager$Stub$Proxy.startInputOrWindowGainedFocus(IInputMethodManager.java:723)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1295)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1538)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3885)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-02 17:15:55.844 32364 32364 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-02 17:15:55.854   791   803 W ActivityManager:   Force finishing activity com.samourai.wallet/.BalanceActivity
03-02 17:15:55.860   791   810 I ActivityManager: Showing crash dialog for package com.samourai.wallet u0
````

Works fine the second time I open it. Nexus 6P, android 8.1.0 (feb 2018 patches)

**Comment by SamouraiDev** [comment]
We will have a look at this. Please refer all tech support issues to support@samouraiwallet.com   Thank you.
