### ISSUE TITLE
Can't connect to Dojo via TOR on Android 5.1 

### ISSUE THREAD

**Issue by stevemyers** [Samourai-Wallet/samourai-wallet-android#367]
Wallet Version: 0.99.87, commit 16926a8
Dojo Version: 1.2.0

I'm getting a TOR error while pairing my side loaded wallet in testnet mode to my testnet Dojo node with an Android 5.1 phone. I do not get this error when pairing my Android 9 phone. Stack trace below. I will try to create a PR for this issue if I can. This issue is to track and get help if anyone has suggestions on how to fix this. 

In particular my tor v3 address can't be resolved, even though TOR seems to be started and the dojo service is up and available and reachable from my TOR browser:

```09-20 10:06:31.087 2981-3073/? W/System.err: java.net.UnknownHostException: Host is unresolved: 75wgon<redacted>.onion```

```
09-20 10:06:31.047 2981-3074/? I/System.out: 10:06:31.046 [RxCachedThreadScheduler-2] INFO com.msopentech.thali.toronionproxy.OnionProxyManager - Tor has already bootstrapped
09-20 10:06:31.052 2981-3073/? I/DojoUtil: setDojoParams: {
        "pairing": {
            "type": "dojo.api",
            "version": "1.2.0",
            "apikey": "<redacted>",
            "url": "http://75wgon<redacted>onion/test/v2"
        }
    }
09-20 10:06:31.053 2981-3073/? D/APIFactory: getToken() url:http://75wgon<redacted>.onion/test/v2/
09-20 10:06:31.053 2981-3073/? I/TorManager: isRequired: true
09-20 10:06:31.053 2981-3073/? I/APIFactory: API key (XOR):<redacted>
09-20 10:06:31.053 2981-30
```73/? I/APIFactory: API key url:http://75wgon<redacted>.onion/test/v2/
09-20 10:06:31.086 2981-3073/? D/OkHttp: --> POST http://75wgon<redacted>.onion/test/v2/auth/login
09-20 10:06:31.086 2981-3073/? D/OkHttp: Content-Type: application/x-www-form-urlencoded
09-20 10:06:31.086 2981-3073/? D/OkHttp: Content-Length: 15
09-20 10:06:31.086 2981-3073/? D/OkHttp: apikey=<redacted>
09-20 10:06:31.086 2981-3073/? D/OkHttp: --> END POST (15-byte body)
09-20 10:06:31.087 2981-3073/? D/OkHttp: <-- HTTP FAILED: java.net.UnknownHostException: Host is unresolved: 75wgon<redacted>.onion
09-20 10:06:31.087 2981-3073/? W/System.err: java.net.UnknownHostException: Host is unresolved: 75wgon<redacted>.onion
09-20 10:06:31.088 2981-3073/? W/System.err:     at java.net.Socket.connect(Socket.java:865)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:71)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
09-20 10:06:31.088 2981-3073/? W/System.err:     at okhttp3.RealCall.execute(RealCall.java:93)
09-20 10:06:31.088 2981-3073/? W/System.err:     at com.samourai.wallet.util.WebUtil.tor_postURL(WebUtil.java:319)
09-20 10:06:31.088 2981-3073/? W/System.err:     at com.samourai.wallet.api.APIFactory.getToken(APIFactory.java:286)
09-20 10:06:31.088 2981-3073/? W/System.err:     at com.samourai.wallet.network.dojo.DojoUtil.lambda$setDojoParams$0(DojoUtil.java:92)
09-20 10:06:31.088 2981-3073/? W/System.err:     at com.samourai.wallet.network.dojo.-$$Lambda$DojoUtil$dGLA6m9OqrbKEb8xJbd5LPw8fUE.call(lambda)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
09-20 10:06:31.088 2981-3073/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
09-20 10:06:31.088 2981-3073/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-20 10:06:31.088 2981-3073/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
09-20 10:06:31.088 2981-3073/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
09-20 10:06:31.089 2981-3073/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-20 10:06:31.089 2981-3073/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-20 10:06:31.089 2981-3073/? W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by stevemyers** [comment]
BTW I was able to repro this issue using an Android Studio using a Nexus 4 emulated phone with Android 5.1, but it is a PITA to find my QR code in the simulated camera scene.

**Comment by stevemyers** [comment]
This issue may be related:  https://github.com/square/okhttp/issues/2315

**Comment by stevemyers** [comment]
Confirmed socket proxy broken also with Android 6 (API 23).  But works fine with Android 7 (API 24).

**Comment by stevemyers** [comment]
Can't fix since it seems to be an Android API problem so closing issue.
