### ISSUE TITLE
Crash on Google Pixel running Android 8.1.0

### ISSUE THREAD

**Issue by eliasnaur** [Samourai-Wallet/samourai-wallet-android#78]
Samourai sometimes crashes for me, even when in the background. I managed to grab a trace with adb logcat:

````
12-10 15:21:29.637 26608 26608 E WindowManager: 
12-10 15:21:29.637 26608 26608 E WindowManager: android.view.WindowLeaked: Activity com.samourai.wallet.BalanceActivity has leaked window DecorView@dca0b72[Samourai] that was originally added here
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.app.Dialog.show(Dialog.java:330)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity$RefreshTask.onPreExecute(BalanceActivity.java:1472)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:648)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity.refreshTx(BalanceActivity.java:1265)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity.access$200(BalanceActivity.java:124)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity$1$1.run(BalanceActivity.java:183)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.app.Activity.runOnUiThread(Activity.java:6174)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity$1.onReceive(BalanceActivity.java:178)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.os.Looper.loop(Looper.java:164)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-10 15:21:29.637 26608 26608 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-10 15:21:29.653 26608 26608 E WindowManager: 
12-10 15:21:29.653 26608 26608 E WindowManager: android.view.WindowLeaked: Activity com.samourai.wallet.BalanceActivity has leaked window DecorView@deff779[Samourai] that was originally added here
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.app.Dialog.show(Dialog.java:330)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity$RefreshTask.onPreExecute(BalanceActivity.java:1472)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:648)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity.refreshTx(BalanceActivity.java:1265)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity.access$200(BalanceActivity.java:124)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity$1$1.run(BalanceActivity.java:183)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.app.Activity.runOnUiThread(Activity.java:6174)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at com.samourai.wallet.BalanceActivity$1.onReceive(BalanceActivity.java:178)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.os.Looper.loop(Looper.java:164)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-10 15:21:29.653 26608 26608 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: FATAL EXCEPTION: main
12-10 15:21:30.062 26608 26608 E AndroidRuntime: Process: com.samourai.wallet, PID: 26608
12-10 15:21:30.062 26608 26608 E AndroidRuntime: java.lang.IllegalArgumentException: View=DecorView@dca0b72[Samourai] not attached to window manager
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:394)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.app.Dialog.dismissDialog(Dialog.java:371)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.app.Dialog.dismiss(Dialog.java:354)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at com.samourai.wallet.BalanceActivity$RefreshTask.onPostExecute(BalanceActivity.java:1647)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at com.samourai.wallet.BalanceActivity$RefreshTask.onPostExecute(BalanceActivity.java:1437)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-10 15:21:30.062 26608 26608 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
````

**Comment by samouraiwallet** [comment]
Thank you for the trace. We'll look into this.

**Comment by SamouraiDev** [comment]
We are now running a few such configurations in-house and have not replicated the issue in the latest updates. If it re-occurs, contact us a support@samouraiwallet.com
